export const BASE_URL = import.meta.env.VITE_API_URL;

export const VIETNAM_CITIES = [
    "An Giang",
    "Bà Rịa - Vũng Tàu",
    "Bắc Giang",
    "Bắc Kạn",
    "Bạc Liêu",
    "Bắc Ninh",
    "Bến Tre",
    "Bình Định",
    "Bình Dương",
    "Bình Phước",
    "Bình Thuận",
    "Cà Mau",
    "Cần Thơ",
    "Cao Bằng",
    "Đà Nẵng",
    "Đắk Lắk",
    "Đắk Nông",
    "Điện Biên",
    "Đồng Nai",
    "Đồng Tháp",
    "Gia Lai",
    "Hà Giang",
    "Hà Nam",
    "Hà Nội",
    "Hà Tĩnh",
    "Hải Dương",
    "Hải Phòng",
    "Hậu Giang",
    "Hòa Bình",
    "Hưng Yên",
    "Khánh Hòa",
    "Kiên Giang",
    "Kon Tum",
    "Lai Châu",
    "Lâm Đồng",
    "Lạng Sơn",
    "Lào Cai",
    "Long An",
    "Nam Định",
    "Nghệ An",
    "Ninh Bình",
    "Ninh Thuận",
    "Phú Thọ",
    "Phú Yên",
    "Quảng Bình",
    "Quảng Nam",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sóc Trăng",
    "Sơn La",
    "Tây Ninh",
    "Thái Bình",
    "Thái Nguyên",
    "Thanh Hóa",
    "Thừa Thiên Huế",
    "Tiền Giang",
    "TP Hồ Chí Minh",
    "Trà Vinh",
    "Tuyên Quang",
    "Vĩnh Long",
    "Vĩnh Phúc",
    "Yên Bái"
];

export const SPORT_OPTIONS = [
    "football",
    "tennis",
    "badminton",
    "pickleball",
    "basketball",
    "volleyball",
    "swimming",
    "gym",
];

export const SPORT_TYPE_OPTIONS = [
    { value: "all", label: "Tất cả" },
    { value: "football", label: "Bóng đá" },
    { value: "tennis", label: "Quần vợt" },
    { value: "badminton", label: "Cầu lông" },
    { value: "pickleball", label: "Pickleball" },
    { value: "basketball", label: "Bóng rổ" },
    { value: "volleyball", label: "Bóng chuyền" },
    { value: "swimming", label: "Bơi lội" },
    { value: "gym", label: "Phòng gym" },
];

export const PRICE_SORT_OPTIONS = [
    { value: "none", label: "Không sắp xếp" },
    { value: "asc", label: "Thấp → Cao" },
    { value: "desc", label: "Cao → Thấp" },
];

export const AMENITY_OPTIONS = [
    "Bãi đỗ xe",
    "Nhà vệ sinh",
    "Quán ăn",
    "Thay đồ",
    "Tắm rửa",
    "WiFi",
    "Đèn chiếu sáng",
];

export const RATING_OPTIONS = [
    { value: "0", label: "Tất cả" },
    { value: "4", label: "Từ 4 sao" },
    { value: "4.5", label: "Từ 4.5 sao" },
    { value: "5", label: "5 sao" },
];

export const WEEKDAY_OPTIONS = [
    { value: "any", label: "Bất kỳ" },
    { value: "mon", label: "Thứ 2" },
    { value: "tue", label: "Thứ 3" },
    { value: "wed", label: "Thứ 4" },
    { value: "thu", label: "Thứ 5" },
    { value: "fri", label: "Thứ 6" },
    { value: "sat", label: "Thứ 7" },
    { value: "sun", label: "Chủ nhật" },
];

export const DISTRICT_OPTIONS = [
    "Quận 1",
    "Quận 2",
    "Quận 3",
    "Quận 4",
    "Quận 5",
    "Quận 6",
    "Quận 7",
    "Quận 8",
    "Quận 9",
    "Quận 10",
    "Quận 11",
    "Quận 12",
    "Bình Thạnh",
    "Tân Bình",
    "Tân Phú",
    "Phú Nhuận",
    "Gò Vấp",
    "Bình Tân",
    "Thủ Đức",
];
