export const BASE_URL = "http://localhost:3000";

export const VIETNAM_CITIES = [
    "Hà Nội",
    "Hồ Chí Minh",
    "Đà Nẵng",
    "Hải Phòng",
    "Cần Thơ",
    "Thái Nguyên",
    "Quảng Ninh",
    "Lạng Sơn",
    "Lào Cai",
    "Bắc Giang",
    "Bắc Ninh",
    "Vĩnh Phúc",
    "Hải Dương",
    "Hưng Yên",
    "Nam Định",
    "Thái Bình",
    "Ninh Bình",
    "Thanh Hóa",
    "Nghệ An",
    "Hà Tĩnh",
    "Quảng Bình",
    "Quảng Trị",
    "Thừa Thiên Huế",
    "Quảng Nam",
    "Quảng Ngãi",
    "Bình Định",
    "Khánh Hòa",
    "Lâm Đồng",
    "Đắk Lắk",
    "Đắk Nông",
    "Bình Dương",
    "Bà Rịa - Vũng Tàu",
    "Đồng Nai",
    "Cà Mau"
];

export const SPORT_OPTIONS = [
    "football",
    "tennis",
    "badminton",
    "pickleball",
    "basketball",
    "volleyball",
    "swimming",
    "gym",
];